openapi: 3.1.0
info:
  title: One Time Password as a Service
  description: Generate and verify a one time password.
  contact:
    email: pastro.craig@gmail.com
  license:
    name: MIT
    url: https://github.com/craigpastro/otpaas/blob/main/LICENSE
  version: 0.0.1
servers:
  - url: https://otpaas.deno.dev
tags:
  - name: otp
paths:
  /v1/get:
    post:
      tags:
        - otp
      summary: Get a OTP
      description: Get a OTP. The default expire time is 10 minutes, but can also be set by setting the "duration" field.
      operationId: getOtp
      requestBody:
        content:
          application/json:
            schema:
              required:
                - id
              type: object
              properties:
                id:
                  type: string
                  example: foo
                duration:
                  type: number
                  example: 600
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                    example: '012345'
                  duration:
                    type: number
                    description: A unix timestamp indicating the time of expiry of the OTP
                    example: 1686110450252
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /v1/verify:
    post:
      tags:
        - otp
      summary: Verify the OTP
      description: Verify the the OTP has not expired and matches the stored one for the given id.
      operationId: verifyOtp
      requestBody:
        content:
          application/json:
            schema:
              required:
                - id
                - password
              type: object
              properties:
                id:
                  type: string
                  example: foo
                password:
                  type: string
                  example: '012345'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  verified:
                    type: boolean
                    example: true
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
